### ISSUE TITLE
`pkl_eval` does not generate proper paths for files generated by Bazel

### ISSUE THREAD

**Issue by mexlez12345** [apple/rules_pkl#21]
version `abab6964bacfbadd20ac3239f13fb9f99a385f4d`

I believe I've found a bug in how `pkl_eval` sets up its `work` subdirectory that breaks when trying to evaluate a generated file .

To reproduce, use this `BUILD` file and try to `bazel build //:eval_entrypoint`

```
genrule(
  name = "gen_entrypoint",
  outs = ["entrypoint.pkl"],
  cmd = """
cat << EOF >> $(location entrypoint.pkl)
x = throw("entrypoint ran!")
EOF
    """
)

pkl_eval(
  name = "eval_entrypoint",
  entrypoints = ["entrypoint.pkl"],
  srcs = [
    "entrypoint.pkl",
  ],
)

```

Error output:
```
–– Pkl Error ––
Cannot find module `file:///<REDACTED_SANDBOX_DIR>/eval_entrypoint/work/bazel-out/linux_x86_64_platform-fastbuild/bin/entrypoint.pkl`.
Failed processing PKL configuration with entrypoint(s) 'bazel-out/linux_x86_64_platform-fastbuild/bin/entrypoint.pkl' (PWD: <REDACTED_SANDBOX_DIR>):

Target //:eval_entrypoint failed to build
```

Poking around in the sandbox, it looks like the file is actually there, but because bazel's expansion the path of the generated `entrypoint.pkl`  includes the `bazel-out` prefix, `pkl` can't find it when its working dir is set to the `work/` subdirectory.

Sandbox contents
```
$ cd <REDACTED_SANDBOX_DIR>
$ tree eval_entrypoint
eval_entrypoint
└── work
    └── entrypoint.pkl -> /<REDACTED_SANDBOX_DIR>/bazel-out/linux_x86_64_platform-fastbuild/bin/entrypoint.pkl

$ ls bazel-out/linux_x86_64_platform-fastbuild/bin/
entrypoint.pkl  eval_entrypoint_symlinks.json
```

**Comment by KushalP** [comment]
@mexlez12345 thank you for the easy to reproduce example. I've opened a PR with a behaviour fix for this case.
